//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Domain
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Canal
	{
		public virtual Queue<Ship> Queue
		{
			get;
			set;
		}

		public virtual {
			get;
			set;
		}

		public virtual Ship ReturnFirstShip()
		{
			throw new System.NotImplementedException();
		}

		public virtual void AddShip()
		{
			throw new System.NotImplementedException();
		}

	}
}

