//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Domain
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Game
	{
		public virtual IEnumerable<Cart> Cart
		{
			get;
			set;
		}

		public virtual Railroad Railroad
		{
			get;
			set;
		}

		public virtual Canal Canal
		{
			get;
			set;
		}

	}
}

